update public.ciudad
set estado = case upper(trim(nombre))
  when 'AGUASCALIENTES' then 'AGUASCALIENTES'
  when 'CANCUN' then 'QUINTANA ROO'
  when 'CDMX' then 'CIUDAD DE MEXICO'
  when 'CIUDAD DE MEXICO' then 'CIUDAD DE MEXICO'
  when 'COAHUILA' then 'COAHUILA'
  when 'CULIACAN' then 'SINALOA'
  when 'CULIACAN ROSALES' then 'SINALOA'
  when 'CUERNAVACA' then 'MORELOS'
  when 'GUADALAJARA' then 'JALISCO'
  when 'GUANAJUATO' then 'GUANAJUATO'
  when 'HERMOSILLO' then 'SONORA'
  when 'HEROICA PUEBLA DE ZARAGOZA' then 'PUEBLA'
  when 'IRAPUATO' then 'GUANAJUATO'
  when 'LEON' then 'GUANAJUATO'
  when 'LEON DE LOS ALDAMA' then 'GUANAJUATO'
  when 'LOS MOCHIS' then 'SINALOA'
  when 'MAZATLAN' then 'SINALOA'
  when 'MERIDA' then 'YUCATAN'
  when 'MONTERREY' then 'NUEVO LEON'
  when 'MOCHIS' then 'SINALOA'
  when 'OAXACA' then 'OAXACA'
  when 'OAXACA DE JUAREZ' then 'OAXACA'
  when 'PUEBLA' then 'PUEBLA'
  when 'PUEBLA DE ZARAGOZA' then 'PUEBLA'
  when 'QUERETARO' then 'QUERETARO'
  when 'REYNOSA' then 'TAMAULIPAS'
  when 'SAN FRANCISCO DEL RINCON' then 'GUANAJUATO'
  when 'SANTIAGO DE QUERETARO' then 'QUERETARO'
  when 'TAMPICO' then 'TAMAULIPAS'
  when 'TIJUANA' then 'BAJA CALIFORNIA'
  when 'TOLUCA' then 'ESTADO DE MEXICO'
  when 'TOLUCA DE LERDO' then 'ESTADO DE MEXICO'
  else estado
end
where estado is null or btrim(estado) = '';
